# Generated by Django 3.1.3 on 2020-11-13 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20201112_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageimg',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageimg',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageimg',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
