# Generated by Django 3.1.3 on 2020-12-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201114_1011'),
        ('article', '0005_auto_20201118_1803'),
    ]

    operations = [
    ]
