# Generated by Django 3.1.3 on 2020-12-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201210_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.ImageField(default='head/default_userHead.png', upload_to='head'),
        ),
    ]
